import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UseSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });
import { Providers } from "../../lib/providers";
import LayoutWrapper from "../app/components/layout-wrapper";

export const metadata: Metadata = {
  title: "Cepat Sehat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <Providers>
          <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
